### ISSUE TITLE
Error when `allOf` is used with contradictory `type`

### ISSUE THREAD

**Issue by kylef** [apiaryio/api-elements.js#266]
For example, the following schema is invalid and cannot be met:

```yaml
allOf:
  - type: array
  - type: string
```

It is not possible to have a type that is both array and string. Thus we cannot create a data structure or valid message body.
